---
title: "Filtering FASTA files for MUSCLE analysis"
author: "Erin Chille"
date: "Last updated 2022/08/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# The following setting is important, do not omit.
options(stringsAsFactors = FALSE) #Set Strings to character
```

# EPI-MACHINE PROJECT

## Set up workspace

Import necessary libraries
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tximport)
library(dplyr)
library(phylotools)
```


Choose which fasta file to clean
```{r}
fasta <- read.fasta(file = "blast_results/raw_fasta_files/HDAC_Sirt.fasta", clean_name = FALSE) #load fasta file
fasta$seq.name <- gsub(" ", "", fasta$seq.name)
fasta$seq.name <- as.factor(fasta$seq.name)
fasta_ref <- fasta[grepl("peptide",fasta$seq.name),]
fasta <- fasta[!grepl("peptide",fasta$seq.name),]
```

Make columns for enzyme, species, and gene
```{r}
fasta <- separate(
  fasta,
  seq.name,
  c("enzyme", "spp"),
  sep = "([|_])",
  remove = FALSE,
  convert = FALSE)
```

Retrieve alignment report
```{r}
stats <- read_csv("blast_results/raw_alignment_reports/HDAC_Sirt_alignment_report.csv", col_names = c("enzyme", "query", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"))
stats$seq.name <- paste(stats$enzyme, stats$query, sep="|")
stats <- stats[,c(13,3:12)]
```

Merge alignment stats and fasta file
```{r}
stat_fasta <- left_join(stats, fasta, by="seq.name"); head(stat_fasta)
stat_fasta <- stat_fasta[,c(1, 12:13, 2:11, 14)]
stat_fasta_clean <- na.omit(stat_fasta)
stat_fasta_clean <- unique(stat_fasta_clean)
stat_fasta_clean_top1 <- stat_fasta_clean %>% group_by(spp, enzyme) %>% slice_max(order_by = bitscore, n = 1, with_ties = FALSE)
```

Merge reference and query fasta sequences
```{r}
clean_fasta_queries <- subset(stat_fasta_clean_top1, select = c("seq.name", "seq.text"))
clean.fasta <- rbind(fasta_ref, clean_fasta_queries)
```

Save new report with sequences and save new fasta file
```{r}
write_csv(stat_fasta_clean_top1, "blast_results/clean_alignment_reports/HDAC_Sirt_allspp_alignment_report_clean.csv")
dat2fasta(clean.fasta, "blast_results/clean_fasta_files/HDAC_Sirt_allspp_clean.fasta")
```

